version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: kubectl-sniff
    main: ./cmd/kubectl-sniff.go
    binary: kubectl-sniff
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.Version={{ .Tag }}
      - -X ksniff/pkg/service/sniffer.DefaultTCPDumpImage=ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | tolower }}/ksniff-tcpdump:{{ .Tag }}
      - -X ksniff/pkg/service/sniffer/runtime.DefaultHelperImage=ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER | tolower }}/ksniff-helper:{{ .Tag }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: kubectl-sniff
    name_template: "kubectl-sniff_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch
