name: k3s-e2e

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: AbsaOSS/k3d-action@v2
        name: "Create single-node cluster"
        with:
          cluster-name: "test-cluster-1"
          args: --agents 1

      - name: Deploy test pod
        run: |
          kubectl config use-context k3d-test-cluster-1
          kubectl create -f .github/workflows/assets/busybox-pod.yaml
          kubectl wait --for=condition=Ready pod/busybox-sleep

      - name: Build
        run: make linux

      - name: Run ksniff ephemeral mode
        run: |
          kubectl config use-context k3d-test-cluster-1
          sleep 60 && pkill kubectl-sniff &
          set +e
          ./kubectl-sniff busybox-sleep --mode ephemeral --namespace default --output-file /tmp/output-ephem.pcap
          set -e
          if [ ! -f /tmp/output-ephem.pcap ]; then
            echo "PCAP not created (ephemeral mode)"
            exit 1
          fi

      - name: Run ksniff privileged mode (deprecated)
        run: |
          kubectl config use-context k3d-test-cluster-1
          sleep 60 && pkill kubectl-sniff &
          set +e
          ./kubectl-sniff busybox-sleep --mode privileged --namespace default --socket /run/k3s/containerd/containerd.sock --output-file /tmp/output-priv.pcap
          set -e
          if [ ! -f /tmp/output-priv.pcap ]; then
            echo "PCAP not created (privileged mode)"
            exit 1
          fi

      - if: failure()
        name: Debug pod state
        run: |
          kubectl get pods
          kubectl get events
