name: minikube-e2e-docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup Minikube
        uses: medyagh/setup-minikube@latest
        with:
          kubernetes-version: v1.31.0
          driver: docker
          wait: all

      - name: Deploy test pod
        run: |
          kubectl create -f .github/workflows/assets/busybox-pod.yaml
          kubectl wait --for=condition=Ready pod/busybox-sleep

      - name: Build
        run: make linux

      - name: Run ksniff ephemeral mode
        run: |
          sleep 60 && pkill kubectl-sniff &
          set +e
          ./kubectl-sniff busybox-sleep --mode ephemeral --namespace default --output-file /tmp/output-ephem.pcap
          set -e
          if [ ! -f /tmp/output-ephem.pcap ]; then
            echo "PCAP not created (ephemeral mode)"
            exit 1
          fi

      - if: failure()
        name: Debug pod state
        run: |
          kubectl get pods
          kubectl get events
