name: unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Copy placeholder kubeconfig
        run: |
          mkdir -p ~/.kube
          cp .github/workflows/assets/placeholder-kubeconfig.yaml ~/.kube/config

      - name: go vet
        run: go vet ./...

      - name: Run tests
        run: go test -race -cover ./...
